Ft transpiling cd
Mucyo-Aime-Christian/MY-BRAND pull request #16
Opened 2020-11-26 15:20 UTC by Mucyo-Aime-Christian

# Queries
- create queries
- retrieve queries
- retrieve a single query
# CRUD
- Create blog
- update blog
- delete blog
- retrieve all and single blog
# comments
- create comments and retrieve them
# authentication
- create/signup user
- login/sign in user
- update profile picture
- remove user
- retrieve users
# Authorization
- protect all my routes with authenticated users
# changing from ES5 to ES6

2020-11-26 15:37 UTC, James-nyagatare reviewed
You can remove those unnecessary comments in signToken.js file and admin.js file also use the method I showed you to remove your .env because it contains some sensitive information. apart from those everything is okay.

2020-11-27 03:57 UTC, harerakalex requested changes
Well done @Mucyo-Aime-Christian

2020-11-27 03:57 UTC, harerakalex commented on server/.env
> +JWT_KEY=dolla
Well, you used the env variable but I can still see it. The aim of the env variable is to hide some important data. For instance third-party API key. Look at your JWT_KEY every can see it.

2020-11-30 09:14 UTC, harerakalex approved these changes

2020-11-30 09:15 UTC, merged