Ft blog page
Mucyo-Aime-Christian/MY-BRAND pull request #2
Opened 2020-10-23 00:57 UTC by Mucyo-Aime-Christian

#implemmenting a blog page where a viewer will be able to view blogs written by users
- responsiveness
- navigation bar
- footer
- blog posts

2020-10-23 06:26 UTC, harerakalex reviewed
well done @Mucyo-Aime-Christian, you did well. I can see that is responsive and looks nice, however, I would suggest that this blog page can be part of your home page and when you click on of those cards then it will redirect you to the page of viewing a single blog.

2020-10-24 09:02 UTC, harerakalex requested changes

2020-10-24 09:02 UTC, harerakalex commented on blog.html
> +        <li><a href="index.html">Home</a></li>
@Mucyo-Aime-Christian, since your home page contains many sections, please use # to link to a given class instead of linking to a new page.

2020-10-24 09:20 UTC, Mucyo-Aime-Christian commented
it is only on the home link that i used link to new page because i want it
to jump to home page

On Sat, Oct 24, 2020 at 11:02 AM harerakalex <notifications@github.com>
wrote:

> *@harerakalex* requested changes on this pull request.
> ------------------------------
>
> In blog.html
> <https://github.com/Mucyo-Aime-Christian/MY-BRAND/pull/2#discussion_r511350863>
> :
>
> > +<head>
> +    <meta charset="UTF-8">
> +<meta name="viewport" content="width=device-width, initial-scale=1">
> +<link rel="stylesheet" href="./css/blog.css">
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
> +<link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
> +<meta http-equiv="X-UA-Compatible" content="ie=edge">
> +<title>MY BRAND</title>
> +</head>
> +<body>
> +<nav class="fixed-nav-bar" id="navbar">
> +    <div class="logo">
> +        <h3><a href="index.html">mr chris</a></h3>
> +    </div>
> +    <ul class="nav-links">
> +        <li><a href="index.html">Home</a></li>
>
> @Mucyo-Aime-Christian <https://github.com/Mucyo-Aime-Christian>, since
> your home page contains many sections, please use # to link to a given
> class instead of linking to a new page.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mucyo-Aime-Christian/MY-BRAND/pull/2#pullrequestreview-516262543>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARLDJKK74QOBZ4LAYWTFZVLSMKJ4DANCNFSM4S3473SA>
> .
>

2020-10-26 09:39 UTC, merged